"use strict";
let mountainList = ["k2", "Mount Everest", "Himalaya"];
let riverList = ["Ravi", "Chenab", "Sutlaj"];
let countryList = ["Pakistan", "India", "Nepal", "Qatar"];
let cityList = ["karachi", "Lahore", "Peshawar", "Quetta"];
let langList = ["English", "Urdu", "Bangali", "Saraiki", "pushto"];
console.log(mountainList);
console.log(riverList);
console.log(countryList);
console.log(cityList);
console.log(langList);
